#!/bin/bash

BOSH_RELEASES_DIR=${BOSH_RELEASES_DIR:-~/workspace}
RELEASE_DIR=${RELEASE_DIR:-$BOSH_RELEASES_DIR/v1-dummy-broker-release}

if [[ ! -d $RELEASE_DIR ]]; then
  echo "Cannot find v1-dummy-broker-release at $RELEASE_DIR; override with \$RELEASE_DIR variable"
  exit 1
fi

cd $RELEASE_DIR
mkdir -p bosh-lite/tmp
mkdir -p bosh-lite/manifests
cp bosh-lite/v1-dummy-broker-stub.yml bosh-lite/tmp/v1-dummy-broker-stub-with-uuid.yml
DIRECTOR_UUID=$(bosh status | grep UUID | awk '{print $2}')
echo $DIRECTOR_UUID
perl -pi -e "s/PLACEHOLDER-DIRECTOR-UUID/$DIRECTOR_UUID/g" bosh-lite/tmp/v1-dummy-broker-stub-with-uuid.yml

bosh target https://192.168.50.4:25555
$RELEASE_DIR/generate_deployment_manifest warden bosh-lite/tmp/v1-dummy-broker-stub-with-uuid.yml > bosh-lite/manifests/v1-dummy-broker-manifest.yml
bosh deployment bosh-lite/manifests/v1-dummy-broker-manifest.yml
