director_uuid: PLACEHOLDER-DIRECTOR-UUID

jobs:
  - name: acceptance-tests
    properties:
      cf:
        admin_username: admin
        admin_password: admin
        skip_ssl_validation: true
properties:
  domain: 10.244.0.34.xip.io

  nats:
    user: nats
    password: nats
    address: 10.244.0.6
    port: 4222

  v1-dummy-broker:
    uaa_client_auth_credentials:
      username: admin
      password: admin
