---
ruby/bundler-1.3.5.gem:
  object_id: 78c06f80-c57f-4db5-9aa3-7349c77b28f2
  sha: !binary |-
    MmNhZDMwNTJhNTliODNmMWY2MTZlODIwMmY1YzcxNGU0NmJkODUyMw==
  size: 268800
ruby/ruby-2.0.0-p353.tar.gz:
  object_id: d5e5fcf4-29c8-4c77-99d2-7d602ad7cf84
  sha: !binary |-
    N2YyYzhiOGY1NjgyYWFiYzExMTRmNDRkMzZkMzE0YzZjMzdjMTFiOA==
  size: 13572794
ruby/rubygems-2.1.11.tgz:
  object_id: ade085d0-8f66-42bc-a748-bc6e10132bcb
  sha: !binary |-
    Y2EzMDMzNDMyY2FlMjhkZWI3Y2VkNzljZGEyNzFjYjI5MmI3MGU1OQ==
  size: 367166
ruby/yaml-0.1.5.tar.gz:
  object_id: 9e08d55b-a3eb-44a3-95f1-14f73e072363
  sha: !binary |-
    OGI3OGNiOWY3NTljN2Q4MGRiOGE3MzI4YzBlYmVjZmUzNGZkZTczNw==
  size: 504897
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: d0c31f71-5afa-493f-8980-1e1654fd6e89
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
ruby/ruby-2.0.0-p481.tar.gz:
  object_id: bbe260c4-86d9-413f-a686-5569faaebbd7
  sha: !binary |-
    ZGRlZDdiNzM0OWQ1OWZlYjgzZDRmNzc0YjJkZGVjMjNlZWFiNzk3OA==
  size: 13586757
