---
ruby/bundler-1.3.5.gem:
  object_id: 7eba9228-785f-42b7-8315-9fe10f04e249
  sha: !binary |-
    MmNhZDMwNTJhNTliODNmMWY2MTZlODIwMmY1YzcxNGU0NmJkODUyMw==
  size: 268800
ruby/ruby-2.0.0-p353.tar.gz:
  object_id: f13bcd6c-a7cb-48d4-b60c-178b5be915d9
  sha: !binary |-
    N2YyYzhiOGY1NjgyYWFiYzExMTRmNDRkMzZkMzE0YzZjMzdjMTFiOA==
  size: 13572794
ruby/rubygems-2.1.11.tgz:
  object_id: 05612435-f24d-4416-9c49-3897c4d5fa0b
  sha: !binary |-
    Y2EzMDMzNDMyY2FlMjhkZWI3Y2VkNzljZGEyNzFjYjI5MmI3MGU1OQ==
  size: 367166
ruby/yaml-0.1.5.tar.gz:
  object_id: da3ee2c1-11f0-4969-a37f-0298f8bf8987
  sha: !binary |-
    OGI3OGNiOWY3NTljN2Q4MGRiOGE3MzI4YzBlYmVjZmUzNGZkZTczNw==
  size: 504897
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: f6ba8121-fb68-4800-998a-57244de40610
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
