meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-lucid-go_agent
    version: (( merge || 2578 ))

compilation:
  network: v1-dummy-broker-network
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( properties.template_only.aws.availability_zone ))

jobs:
  - name: v1-dummy-node
    instances: 1
    networks:
    - name: v1-dummy-broker-network
      static_ips: (( static_ips(11) ))
  - name: v1-dummy-broker
    instances: 1
    networks:
    - name: v1-dummy-broker-network
      static_ips: (( static_ips(10) ))
  - name: acceptance-tests
    instances: 1
    networks:
    - name: v1-dummy-broker-network
networks:
  - name: v1-dummy-broker-network
    type: manual
    subnets:
    - name: default_unused
      range: 10.10.32.0/20
      reserved:
        - 10.10.32.2 - 10.10.36.255
        - 10.10.38.1 - 10.10.47.254
      static:
        - 10.10.37.1 - 10.10.37.255
      gateway: 10.10.32.1
      dns:
        - 10.10.0.2
      cloud_properties:
        security_groups:
        - cf
        subnet: (( properties.template_only.aws.subnet_ids.services1 ))

resource_pools:
  - name: services-small
    stemcell: (( meta.stemcell ))
    network: v1-dummy-broker-network
    cloud_properties:
      instance_type: m1.small
      availability_zone: (( properties.template_only.aws.availability_zone ))

properties:
  template_only: (( merge ))
