meta:
  stemcell:
    name: bosh-aws-xen-ubuntu-trusty-go_agent
    version: 2719.3

compilation:
  network: v1-dummy-broker-network
  cloud_properties:
    instance_type: c1.medium
    availability_zone: (( properties.template_only.aws.availability_zone ))

jobs:
  - name: v1-dummy-node
    instances: 1
    networks:
    - name: v1-dummy-broker-network
      static_ips: (( static_ips(11) ))
  - name: v1-dummy-broker
    instances: 1
    networks:
    - name: v1-dummy-broker-network
      static_ips: (( static_ips(10) ))
  - name: acceptance-tests
    instances: 1
    networks:
    - name: v1-dummy-broker-network
networks: (( merge ))

resource_pools:
  - name: services-small
    stemcell:
      name: (( meta.stemcell.name ))
      version: (( merge || meta.stemcell.version ))
    network: v1-dummy-broker-network
    cloud_properties:
      instance_type: m3.medium
      availability_zone: (( properties.template_only.aws.availability_zone ))

properties:
  template_only: (( merge ))
