---
name: v1-dummy-broker
director_uuid: (( merge ))
releases:
  - name: v1-dummy-broker
    version: latest

jobs:
  - name : v1-dummy-node
    instances: 1
    release: v1-dummy-broker
    resource_pool: services-small
    template: v1-dummy-node
    networks: (( merge ))
    properties:
      networks:
        broker_network: (( jobs.v1-dummy-broker.networks.[0].name ))
      env:
        service_unique_id: v1-dummy-broker-service
        plan_unique_id: v1-dummy-broker-plan
        pid_file: /var/vcap/sys/run/v1-dummy-node/v1-dummy-node.pid
        uaa_endpoint: (( .properties.http_scheme "uaa." .properties.domain ))
        cloud_controller_uri: (( .properties.http_scheme "api." .properties.domain ))
        uaa_client_id: cf
        uaa_username: (( .properties.v1-dummy-broker.uaa_client_auth_credentials.username ))
        uaa_password: (( .properties.v1-dummy-broker.uaa_client_auth_credentials.password ))
        nats: (( .properties.nats ))
        service_auth_token: 36001246-f5d0-4d9a-aa33-7d2522fe1ea7
        app_domain: (( .properties.app_domains.[0] ))
  - name: v1-dummy-broker
    instances: 1
    release: v1-dummy-broker
    resource_pool: services-small
    template: v1-dummy-broker
    networks: (( merge ))
    properties:
      networks:
        broker_network: (( jobs.v1-dummy-broker.networks.[0].name ))
      env:
        service_unique_id: v1-dummy-broker-service
        plan_unique_id: v1-dummy-broker-plan
        pid_file: /var/vcap/sys/run/v1-dummy-broker/v1-dummy-broker.pid
        uaa_endpoint: (( .properties.http_scheme "uaa." .properties.domain ))
        cloud_controller_uri: (( .properties.http_scheme "api." .properties.domain ))
        uaa_client_id: cf
        uaa_username: (( .properties.v1-dummy-broker.uaa_client_auth_credentials.username ))
        uaa_password: (( .properties.v1-dummy-broker.uaa_client_auth_credentials.password ))
        nats: (( .properties.nats ))
        service_auth_token: 36001246-f5d0-4d9a-aa33-7d2522fe1ea7
  - name: acceptance-tests
    template: acceptance-tests
    release: v1-dummy-broker
    instances: 1
    resource_pool: services-small
    lifecycle: errand
    networks: (( merge ))
    properties:
      cf:
        api_url: (( .properties.http_scheme "api." .properties.domain ))
        admin_username: (( merge ))
        admin_password: (( merge ))
        apps_domain: (( .properties.app_domains.[0] ))
        skip_ssl_validation: (( merge || false ))

update:
  canaries: 1
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 4
  max_errors: 1

compilation:
  workers: 1
  reuse_compilation_vms: true
  network: (( merge ))
  cloud_properties: (( merge )) 

properties:
  domain: (( merge ))
  nats:
    port: (( merge ))
    machines: (( merge ))
    address: (( machines.[0] ))
    user: (( merge ))
    password: (( merge ))
  v1-dummy-broker: (( merge ))
  app_domains: (( merge ))
  http_scheme: (( merge ))

resource_pools:
  - name: services-small
    stemcell: (( merge ))
    network: (( merge ))
    cloud_properties: (( merge ))

networks: (( merge ))
